name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: electron-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test

  build-windows:
    needs: test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: electron-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build:win
      - uses: actions/upload-artifact@v4
        with:
          name: SAT-XML-Conversor-Windows
          path: electron-app/dist/*.exe

  build-mac:
    needs: test
    runs-on: macos-latest
    defaults:
      run:
        working-directory: electron-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build:mac
      - uses: actions/upload-artifact@v4
        with:
          name: SAT-XML-Conversor-macOS
          path: electron-app/dist/*.dmg
